name: effort
description: "A gym app"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utility packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^2.7.0
  mime: ^1.0.5
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  flutter_dotenv: ^5.0.2

  # Video and Image
  video_player: ^2.8.6
  image_picker: ^0.8.4+2
  file_picker: ^5.0.0
  path: ^1.8.3
  path_provider: ^2.1.3

  # Muscle Selector
  muscle_selector: ^1.0.3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # gRPC
  grpc: ^3.2.4
  protobuf: ^3.1.0

  # Graphs
  fl_chart: ^0.40.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Local Assetes
  assets:
    - .env
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/user/
